server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/,http://127.0.0.1:7003/eureka/ #往该地址注册自己的信息到注册中心
  instance:
    instance-id: provider-service-8001 # 自定义服务名称信息
    prefer-ip-address: true # 访问路径可以显示ip信息

info:
  app.name: provider-service-8001
  company.name: www.bdqn.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$

spring:
  application:
    name: provider-service  # 指明微服务应用名，这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name。


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
    mode: HTML5
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url:  jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password: root
  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            #isClustered: false
            #clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: jdbc

  profiles:
    active: dev
logging:
  config: classpath:logback-spring.xml
  level:
    cn.bdqn.mapper: debug  # 解决mybatis sql不打印问题
mybatis:
  # mybatis主配置文件
  # config-location: classpath:mybatis/mybatis-config.xml
  # 映射文件所在路径
  mapper-locations: classpath:mybatis/mapper/*.xml
  # pojo类所在包路径。
  type-aliases-package: cn.bdqn.entity
  